language: python
python:
 - "2.6"
 - "2.7"
 - "3.4"
 - "3.5"
 - "3.6"
 - "3.7"
 - "3.8-dev"
 - "pypy"
 - "pypy3.5"
 - "pypy3.6"
install:
 - pip install -r requirements.txt
 - python setup.py install
script: py.test --assert=plain

